"""Enums for the pure Paper execution lifecycle core."""

from __future__ import annotations

from enum import StrEnum


class PaperExecutionLifecycleState(StrEnum):
    """Accepted ADR-006 lifecycle states."""

    CREATED = "CREATED"
    ELIGIBILITY_EVALUATED = "ELIGIBILITY_EVALUATED"
    INELIGIBLE = "INELIGIBLE"
    APPROVAL_CONFIRMED = "APPROVAL_CONFIRMED"
    IDEMPOTENCY_RESERVED = "IDEMPOTENCY_RESERVED"
    READY_FOR_DISPATCH = "READY_FOR_DISPATCH"
    DISPATCH_PENDING = "DISPATCH_PENDING"
    DISPATCHED = "DISPATCHED"
    BROKER_ACKNOWLEDGED = "BROKER_ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCELLED = "CANCELLED"
    REPLACE_REQUESTED = "REPLACE_REQUESTED"
    REPLACE_PENDING = "REPLACE_PENDING"
    REPLACED = "REPLACED"
    BROKER_REJECTED = "BROKER_REJECTED"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    FAILED_TERMINAL = "FAILED_TERMINAL"
    ABORTED_BEFORE_DISPATCH = "ABORTED_BEFORE_DISPATCH"


class PaperExecutionLifecycleInputType(StrEnum):
    """Accepted ADR-006 lifecycle inputs and observations."""

    CREATE_AGGREGATE = "CREATE_AGGREGATE"
    RECORD_ELIGIBILITY = "RECORD_ELIGIBILITY"
    RECORD_INELIGIBLE = "RECORD_INELIGIBLE"
    RECORD_INDETERMINATE = "RECORD_INDETERMINATE"
    RECORD_APPROVAL = "RECORD_APPROVAL"
    RECORD_IDEMPOTENCY_RESERVATION = "RECORD_IDEMPOTENCY_RESERVATION"
    PREPARE_DISPATCH = "PREPARE_DISPATCH"
    RECORD_DISPATCH_PENDING = "RECORD_DISPATCH_PENDING"
    RECORD_DISPATCH = "RECORD_DISPATCH"
    OBSERVE_BROKER_ACKNOWLEDGEMENT = "OBSERVE_BROKER_ACKNOWLEDGEMENT"
    OBSERVE_BROKER_REJECTION = "OBSERVE_BROKER_REJECTION"
    OBSERVE_PARTIAL_FILL = "OBSERVE_PARTIAL_FILL"
    OBSERVE_FILL = "OBSERVE_FILL"
    REQUEST_CANCELLATION = "REQUEST_CANCELLATION"
    RECORD_CANCELLATION_PENDING = "RECORD_CANCELLATION_PENDING"
    OBSERVE_CANCELLATION_CONFIRMATION = "OBSERVE_CANCELLATION_CONFIRMATION"
    REQUEST_REPLACEMENT = "REQUEST_REPLACEMENT"
    RECORD_REPLACEMENT_PENDING = "RECORD_REPLACEMENT_PENDING"
    OBSERVE_REPLACEMENT_CONFIRMATION = "OBSERVE_REPLACEMENT_CONFIRMATION"
    MARK_OUTCOME_UNKNOWN = "MARK_OUTCOME_UNKNOWN"
    REQUIRE_RECONCILIATION = "REQUIRE_RECONCILIATION"
    RECORD_RECONCILIATION_RESULT = "RECORD_RECONCILIATION_RESULT"
    ABORT_BEFORE_DISPATCH = "ABORT_BEFORE_DISPATCH"
    FAIL_TERMINALLY = "FAIL_TERMINALLY"


class PaperExecutionLifecycleInputCategory(StrEnum):
    """Lifecycle input ownership categories."""

    APPLICATION = "APPLICATION"
    INTERNAL = "INTERNAL"
    BROKER_OBSERVATION = "BROKER_OBSERVATION"
    RECONCILIATION = "RECONCILIATION"


class PaperExecutionTransitionDecisionType(StrEnum):
    """Transition decision classification."""

    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REPLAYED = "REPLAYED"
    COMMAND_CONFLICT = "COMMAND_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    BROKER_OBSERVATION_CONFLICT = "BROKER_OBSERVATION_CONFLICT"


class PaperExecutionReplayKind(StrEnum):
    """Replay and duplicate classification."""

    NONE = "NONE"
    COMMAND_REPLAY = "COMMAND_REPLAY"
    IDEMPOTENCY_REPLAY = "IDEMPOTENCY_REPLAY"
    BROKER_OBSERVATION_REPLAY = "BROKER_OBSERVATION_REPLAY"
    RECONCILIATION_REPLAY = "RECONCILIATION_REPLAY"


class PaperExecutionLifecycleSideEffectIntentKind(StrEnum):
    """Descriptive future side-effect intent kinds only."""

    NONE = "NONE"
    WOULD_RESERVE_IDEMPOTENCY = "WOULD_RESERVE_IDEMPOTENCY"
    WOULD_PREPARE_DISPATCH = "WOULD_PREPARE_DISPATCH"
    WOULD_DISPATCH = "WOULD_DISPATCH"
    WOULD_REQUEST_CANCEL = "WOULD_REQUEST_CANCEL"
    WOULD_REQUEST_REPLACE = "WOULD_REQUEST_REPLACE"
    WOULD_QUERY_STATUS = "WOULD_QUERY_STATUS"
    WOULD_RECONCILE = "WOULD_RECONCILE"
    WOULD_NOTIFY_OPERATOR = "WOULD_NOTIFY_OPERATOR"


class PaperExecutionLifecycleEvidenceIntentKind(StrEnum):
    """Descriptive future evidence intent kinds only."""

    LIFECYCLE_TRANSITION_ACCEPTED = "LIFECYCLE_TRANSITION_ACCEPTED"
    LIFECYCLE_TRANSITION_REJECTED = "LIFECYCLE_TRANSITION_REJECTED"
    LIFECYCLE_REPLAYED = "LIFECYCLE_REPLAYED"
    LIFECYCLE_COMMAND_CONFLICT = "LIFECYCLE_COMMAND_CONFLICT"
    LIFECYCLE_IDEMPOTENCY_CONFLICT = "LIFECYCLE_IDEMPOTENCY_CONFLICT"
    LIFECYCLE_BROKER_OBSERVATION_REPLAYED = "LIFECYCLE_BROKER_OBSERVATION_REPLAYED"
    LIFECYCLE_BROKER_OBSERVATION_CONFLICT = "LIFECYCLE_BROKER_OBSERVATION_CONFLICT"
    LIFECYCLE_OUTCOME_UNKNOWN = "LIFECYCLE_OUTCOME_UNKNOWN"
    LIFECYCLE_RECONCILIATION_REQUIRED = "LIFECYCLE_RECONCILIATION_REQUIRED"
    LIFECYCLE_TERMINAL_STATE_REACHED = "LIFECYCLE_TERMINAL_STATE_REACHED"


class PaperExecutionReconciliationOutcome(StrEnum):
    """Bounded reconciliation outcomes accepted by Sentinel."""

    CONSISTENT = "CONSISTENT"
    LOCAL_AHEAD = "LOCAL_AHEAD"
    BROKER_AHEAD = "BROKER_AHEAD"
    MISSING_LOCALLY = "MISSING_LOCALLY"
    MISSING_AT_BROKER = "MISSING_AT_BROKER"
    CONFLICTING = "CONFLICTING"
    UNRESOLVED = "UNRESOLVED"
    OPERATOR_ACTION_REQUIRED = "OPERATOR_ACTION_REQUIRED"


class PaperExecutionLifecycleGuard(StrEnum):
    """Stable guard identifiers used by transition specifications."""

    EXPECTED_REVISION_MATCHES = "EXPECTED_REVISION_MATCHES"
    PAPER_MODE_CONFIRMED = "PAPER_MODE_CONFIRMED"
    IDENTITY_MATCHES = "IDENTITY_MATCHES"
    ELIGIBILITY_RECORDED = "ELIGIBILITY_RECORDED"
    ELIGIBILITY_COMPATIBLE = "ELIGIBILITY_COMPATIBLE"
    APPROVAL_VALID = "APPROVAL_VALID"
    IDEMPOTENCY_CONFIRMED = "IDEMPOTENCY_CONFIRMED"
    EMERGENCY_STOP_CLEAR = "EMERGENCY_STOP_CLEAR"
    BROKER_REFERENCE_PRESENT = "BROKER_REFERENCE_PRESENT"
    BROKER_OBSERVATION_IDENTITY_PRESENT = "BROKER_OBSERVATION_IDENTITY_PRESENT"
    FILL_MONOTONIC = "FILL_MONOTONIC"
    CANCELLATION_VALID = "CANCELLATION_VALID"
    REPLACEMENT_VALID = "REPLACEMENT_VALID"
    RECONCILIATION_DESTINATION_BOUNDED = "RECONCILIATION_DESTINATION_BOUNDED"
