"""Enums for inert Paper execution contracts."""

from __future__ import annotations

from enum import StrEnum


class PaperExecutionMode(StrEnum):
    """Execution mode. Paper is the only supported mode."""

    PAPER = "PAPER"


class PaperExecutionOperation(StrEnum):
    """State-changing operations only."""

    SUBMIT = "SUBMIT"
    CANCEL = "CANCEL"
    REPLACE = "REPLACE"


class PaperExecutionSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class PaperExecutionOrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class PaperExecutionTimeInForce(StrEnum):
    DAY = "DAY"
    GTC = "GTC"


class PaperExecutionStatus(StrEnum):
    CREATED = "CREATED"
    REJECTED_LOCAL = "REJECTED_LOCAL"
    RESERVED = "RESERVED"
    DISPATCHED = "DISPATCHED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    WORKING = "WORKING"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCELLED = "CANCELLED"
    REPLACE_PENDING = "REPLACE_PENDING"
    REPLACED = "REPLACED"
    BROKER_REJECTED = "BROKER_REJECTED"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class PaperExecutionReceiptKind(StrEnum):
    COMMAND_ACCEPTED_LOCALLY = "COMMAND_ACCEPTED_LOCALLY"
    DISPATCH_RECORDED = "DISPATCH_RECORDED"
    BROKER_ACKNOWLEDGED = "BROKER_ACKNOWLEDGED"
    BROKER_REJECTED = "BROKER_REJECTED"
    PARTIAL_FILL_OBSERVED = "PARTIAL_FILL_OBSERVED"
    FILL_OBSERVED = "FILL_OBSERVED"
    CANCEL_ACKNOWLEDGED = "CANCEL_ACKNOWLEDGED"
    CANCEL_CONFIRMED = "CANCEL_CONFIRMED"
    REPLACE_ACKNOWLEDGED = "REPLACE_ACKNOWLEDGED"
    REPLACE_CONFIRMED = "REPLACE_CONFIRMED"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class PaperExecutionFailureKind(StrEnum):
    CONTRACT_VALIDATION = "CONTRACT_VALIDATION"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_INVALID = "APPROVAL_INVALID"
    PAPER_MODE_VIOLATION = "PAPER_MODE_VIOLATION"
    STALE_REVISION = "STALE_REVISION"
    DUPLICATE_CONFLICT = "DUPLICATE_CONFLICT"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_TIME_IN_FORCE = "INVALID_TIME_IN_FORCE"
    MARKET_CLOSED = "MARKET_CLOSED"
    BROKER_UNAVAILABLE = "BROKER_UNAVAILABLE"
    TRANSPORT_TIMEOUT = "TRANSPORT_TIMEOUT"
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
    AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE"
    RATE_LIMITED = "RATE_LIMITED"
    BROKER_REJECTED = "BROKER_REJECTED"
    ACKNOWLEDGEMENT_AMBIGUOUS = "ACKNOWLEDGEMENT_AMBIGUOUS"
    OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
    CANCELLATION_RACE = "CANCELLATION_RACE"
    REPLACEMENT_RACE = "REPLACEMENT_RACE"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
    PERSISTENCE_FAILURE = "PERSISTENCE_FAILURE"
    INTERNAL_INVARIANT = "INTERNAL_INVARIANT"


class PaperExecutionFailureSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class PaperExecutionApprovalKind(StrEnum):
    OPERATOR = "OPERATOR"
    SYSTEM_POLICY = "SYSTEM_POLICY"
    STRATEGY = "STRATEGY"
