CREATE TABLE execution_dispatch_controls (
    control_id TEXT PRIMARY KEY CHECK (control_id = 'PAPER_DISPATCH'), enabled INTEGER NOT NULL CHECK (enabled IN (0,1)), paper_mode INTEGER NOT NULL CHECK (paper_mode = 1), emergency_stop_active INTEGER NOT NULL CHECK (emergency_stop_active IN (0,1)), legacy_authority_active INTEGER NOT NULL CHECK (legacy_authority_active IN (0,1)), generation INTEGER NOT NULL CHECK (generation >= 1), updated_at TEXT NOT NULL, schema_version TEXT NOT NULL CHECK (schema_version = '4'), record_fingerprint TEXT NOT NULL
);
INSERT INTO execution_dispatch_controls VALUES ('PAPER_DISPATCH',0,1,1,1,1,'1970-01-01T00:00:00.000000Z','4','pdc-fail-closed-v004');

CREATE TABLE execution_dispatch_claims (
    claim_token TEXT PRIMARY KEY, submission_id TEXT NOT NULL UNIQUE, command_id TEXT NOT NULL UNIQUE REFERENCES execution_commands(command_id), aggregate_id TEXT NOT NULL REFERENCES execution_aggregates(aggregate_id), correlation_id TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE REFERENCES execution_idempotency(idempotency_key), expected_execution_revision INTEGER NOT NULL CHECK (expected_execution_revision >= 0), request_fingerprint TEXT NOT NULL, command_record_fingerprint TEXT NOT NULL, canonical_payload_fingerprint TEXT NOT NULL, approval_fingerprint TEXT NOT NULL, policy_fingerprint TEXT NOT NULL, client_order_id TEXT NOT NULL UNIQUE CHECK (length(client_order_id) = 48), capability_verifier TEXT NOT NULL UNIQUE CHECK (length(capability_verifier) = 68 AND substr(capability_verifier,1,4) = 'pcv-' AND substr(capability_verifier,5) NOT GLOB '*[^0-9a-f]*'), canonical_order_json TEXT NOT NULL, control_generation INTEGER NOT NULL CHECK (control_generation >= 1), claimed_at TEXT NOT NULL, mode TEXT NOT NULL CHECK (mode = 'PAPER'), schema_version TEXT NOT NULL CHECK (schema_version = '4'), record_fingerprint TEXT NOT NULL UNIQUE
);
CREATE TABLE execution_dispatch_authorizations (
    claim_token TEXT PRIMARY KEY REFERENCES execution_dispatch_claims(claim_token), authorization_fingerprint TEXT NOT NULL UNIQUE, control_generation INTEGER NOT NULL CHECK (control_generation >= 1), authorized_at TEXT NOT NULL, schema_version TEXT NOT NULL CHECK (schema_version = '4'), record_fingerprint TEXT NOT NULL UNIQUE
);
CREATE UNIQUE INDEX idx_execution_broker_references_exact_owner ON execution_broker_references(broker_reference, aggregate_id, command_id, record_fingerprint);
CREATE TABLE execution_dispatch_resolutions (
    claim_token TEXT PRIMARY KEY REFERENCES execution_dispatch_claims(claim_token), resolution_status TEXT NOT NULL CHECK (resolution_status IN ('PRE_EFFECT_BLOCKED','ACKNOWLEDGED','BROKER_REJECTED','OUTCOME_UNKNOWN','EVIDENCE_RECORDING_FAILED','BROKER_REFERENCE_CONFLICT')), effect_phase TEXT NOT NULL CHECK (effect_phase IN ('PRE_EFFECT','POSSIBLE_POST_EFFECT','POST_EFFECT_OBSERVED')), resolved_at TEXT NOT NULL, broker_reference TEXT, observation_fingerprint TEXT, conflicting_owner_aggregate_id TEXT, conflicting_owner_command_id TEXT, conflicting_owner_record_fingerprint TEXT, result_fingerprint TEXT NOT NULL, evidence_fingerprint TEXT NOT NULL, evidence_record_fingerprint TEXT NOT NULL, safe_reason_code TEXT NOT NULL, reconciliation_required INTEGER NOT NULL CHECK (reconciliation_required IN (0,1)), operator_action_required INTEGER NOT NULL CHECK (operator_action_required IN (0,1)), automatic_retry INTEGER NOT NULL CHECK (automatic_retry = 0), schema_version TEXT NOT NULL CHECK (schema_version = '4'), record_fingerprint TEXT NOT NULL UNIQUE,
    CHECK (resolution_status NOT IN ('OUTCOME_UNKNOWN','EVIDENCE_RECORDING_FAILED','BROKER_REFERENCE_CONFLICT') OR reconciliation_required = 1),
    CHECK ((resolution_status = 'BROKER_REFERENCE_CONFLICT' AND broker_reference IS NOT NULL AND conflicting_owner_aggregate_id IS NOT NULL AND conflicting_owner_command_id IS NOT NULL AND conflicting_owner_record_fingerprint IS NOT NULL) OR (resolution_status <> 'BROKER_REFERENCE_CONFLICT' AND conflicting_owner_aggregate_id IS NULL AND conflicting_owner_command_id IS NULL AND conflicting_owner_record_fingerprint IS NULL)),
    FOREIGN KEY (broker_reference, conflicting_owner_aggregate_id, conflicting_owner_command_id, conflicting_owner_record_fingerprint) REFERENCES execution_broker_references(broker_reference, aggregate_id, command_id, record_fingerprint)
);
CREATE INDEX idx_execution_dispatch_claims_aggregate_revision ON execution_dispatch_claims(aggregate_id, expected_execution_revision);
CREATE INDEX idx_execution_dispatch_claims_command_request ON execution_dispatch_claims(command_id, request_fingerprint);
CREATE INDEX idx_execution_dispatch_claims_idempotency_payload ON execution_dispatch_claims(idempotency_key, canonical_payload_fingerprint);
CREATE TRIGGER trg_execution_dispatch_controls_generation BEFORE UPDATE ON execution_dispatch_controls WHEN NEW.generation <> OLD.generation + 1 BEGIN SELECT RAISE(ABORT, 'execution_dispatch_controls generation must increment by one'); END;
CREATE TRIGGER trg_execution_dispatch_claims_no_update BEFORE UPDATE ON execution_dispatch_claims BEGIN SELECT RAISE(ABORT, 'execution_dispatch_claims is immutable'); END;
CREATE TRIGGER trg_execution_dispatch_claims_no_delete BEFORE DELETE ON execution_dispatch_claims BEGIN SELECT RAISE(ABORT, 'execution_dispatch_claims is immutable'); END;
CREATE TRIGGER trg_execution_dispatch_authorizations_no_update BEFORE UPDATE ON execution_dispatch_authorizations BEGIN SELECT RAISE(ABORT, 'execution_dispatch_authorizations is immutable'); END;
CREATE TRIGGER trg_execution_dispatch_authorizations_no_delete BEFORE DELETE ON execution_dispatch_authorizations BEGIN SELECT RAISE(ABORT, 'execution_dispatch_authorizations is immutable'); END;
CREATE TRIGGER trg_execution_dispatch_resolutions_no_update BEFORE UPDATE ON execution_dispatch_resolutions BEGIN SELECT RAISE(ABORT, 'execution_dispatch_resolutions is immutable'); END;
CREATE TRIGGER trg_execution_dispatch_resolutions_no_delete BEFORE DELETE ON execution_dispatch_resolutions BEGIN SELECT RAISE(ABORT, 'execution_dispatch_resolutions is immutable'); END;
