"""Enums for pure Paper execution eligibility evaluation."""

from __future__ import annotations

from enum import StrEnum


class PaperExecutionEligibilityDecision(StrEnum):
    """Top-level advisory eligibility decisions."""

    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    INDETERMINATE = "INDETERMINATE"


class PaperExecutionEligibilityCriterion(StrEnum):
    """Stable deterministic eligibility criteria."""

    COMMAND_TYPE_VALID = "COMMAND_TYPE_VALID"
    PAPER_MODE_VALID = "PAPER_MODE_VALID"
    OPERATION_ALLOWED = "OPERATION_ALLOWED"
    COMMAND_IDENTITY_PRESENT = "COMMAND_IDENTITY_PRESENT"
    PAYLOAD_FINGERPRINT_VALID = "PAYLOAD_FINGERPRINT_VALID"
    AGGREGATE_IDENTITY_VALID = "AGGREGATE_IDENTITY_VALID"
    CORRELATION_IDENTITY_VALID = "CORRELATION_IDENTITY_VALID"
    IDEMPOTENCY_KEY_PRESENT = "IDEMPOTENCY_KEY_PRESENT"
    IDEMPOTENCY_KEY_CONSISTENT = "IDEMPOTENCY_KEY_CONSISTENT"
    EXPECTED_REVISION_VALID = "EXPECTED_REVISION_VALID"
    OPERATION_REVISION_COMPATIBLE = "OPERATION_REVISION_COMPATIBLE"
    INTENT_COMPATIBLE = "INTENT_COMPATIBLE"
    APPROVAL_PRESENT = "APPROVAL_PRESENT"
    APPROVAL_BINDING_VALID = "APPROVAL_BINDING_VALID"
    APPROVAL_TIME_VALID = "APPROVAL_TIME_VALID"
    POLICY_SNAPSHOT_COMPATIBLE = "POLICY_SNAPSHOT_COMPATIBLE"
    CONTEXT_CONSISTENT = "CONTEXT_CONSISTENT"
    NO_READINESS_AUTHORITY = "NO_READINESS_AUTHORITY"
    EXTERNAL_MARKET_CAPABILITY_STATUS = "EXTERNAL_MARKET_CAPABILITY_STATUS"
    EXTERNAL_EMERGENCY_STOP_STATUS = "EXTERNAL_EMERGENCY_STOP_STATUS"
    EXTERNAL_RISK_STATUS = "EXTERNAL_RISK_STATUS"
    EXTERNAL_ACCOUNT_STATUS = "EXTERNAL_ACCOUNT_STATUS"


class PaperExecutionEligibilityCriterionOutcome(StrEnum):
    """Per-criterion outcome."""

    PASS = "PASS"
    FAIL = "FAIL"
    UNRESOLVED = "UNRESOLVED"


class PaperExecutionEligibilityFailureCode(StrEnum):
    """Stable reason codes for eligibility results."""

    ELIGIBLE = "ELIGIBLE"
    INVALID_COMMAND_TYPE = "INVALID_COMMAND_TYPE"
    PAPER_MODE_REQUIRED = "PAPER_MODE_REQUIRED"
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    COMMAND_IDENTITY_INVALID = "COMMAND_IDENTITY_INVALID"
    PAYLOAD_FINGERPRINT_MISMATCH = "PAYLOAD_FINGERPRINT_MISMATCH"
    AGGREGATE_IDENTITY_MISMATCH = "AGGREGATE_IDENTITY_MISMATCH"
    CORRELATION_IDENTITY_MISMATCH = "CORRELATION_IDENTITY_MISMATCH"
    IDEMPOTENCY_KEY_MISSING = "IDEMPOTENCY_KEY_MISSING"
    IDEMPOTENCY_KEY_UNVERIFIABLE = "IDEMPOTENCY_KEY_UNVERIFIABLE"
    EXPECTED_REVISION_INVALID = "EXPECTED_REVISION_INVALID"
    INITIAL_SUBMIT_REVISION_REQUIRED = "INITIAL_SUBMIT_REVISION_REQUIRED"
    INTENT_REQUIRED = "INTENT_REQUIRED"
    INTENT_NOT_ALLOWED = "INTENT_NOT_ALLOWED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_BINDING_MISMATCH = "APPROVAL_BINDING_MISMATCH"
    APPROVAL_NOT_YET_VALID = "APPROVAL_NOT_YET_VALID"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    EVALUATION_TIME_REQUIRED = "EVALUATION_TIME_REQUIRED"
    POLICY_SNAPSHOT_INCOMPATIBLE = "POLICY_SNAPSHOT_INCOMPATIBLE"
    CONTEXT_INCONSISTENT = "CONTEXT_INCONSISTENT"
    MARKET_CAPABILITY_CLEARANCE_REQUIRED = "MARKET_CAPABILITY_CLEARANCE_REQUIRED"
    EMERGENCY_STOP_CLEARANCE_REQUIRED = "EMERGENCY_STOP_CLEARANCE_REQUIRED"
    RISK_CLEARANCE_REQUIRED = "RISK_CLEARANCE_REQUIRED"
    ACCOUNT_CLEARANCE_REQUIRED = "ACCOUNT_CLEARANCE_REQUIRED"
    EXTERNAL_EVIDENCE_REQUIRED = "EXTERNAL_EVIDENCE_REQUIRED"


class PaperExecutionEligibilitySeverity(StrEnum):
    """Stable criterion severity."""

    INFO = "INFO"
    BLOCKING = "BLOCKING"
    UNRESOLVED = "UNRESOLVED"
