"""Enums for deterministic Paper execution dry-run orchestration."""

from __future__ import annotations

from enum import StrEnum


class PaperExecutionEffectMode(StrEnum):
    """Execution effect mode; dry-run is the only supported effect."""

    DRY_RUN = "DRY_RUN"


class PaperDryRunOutcomeKind(StrEnum):
    """Dry-run outcome classification with no broker-truth claims."""

    WOULD_DISPATCH = "WOULD_DISPATCH"
    WOULD_REJECT = "WOULD_REJECT"
    WOULD_REQUIRE_EXTERNAL_EVIDENCE = "WOULD_REQUIRE_EXTERNAL_EVIDENCE"
    WOULD_REQUIRE_RECONCILIATION = "WOULD_REQUIRE_RECONCILIATION"
    NO_ACTION_REPLAY = "NO_ACTION_REPLAY"


class PaperDryRunStepKind(StrEnum):
    """Stable orchestration step kinds emitted by the dry-run executor."""

    REQUEST_VALIDATED = "REQUEST_VALIDATED"
    ELIGIBILITY_EVALUATED = "ELIGIBILITY_EVALUATED"
    ELIGIBILITY_REJECTED = "ELIGIBILITY_REJECTED"
    ELIGIBILITY_INDETERMINATE = "ELIGIBILITY_INDETERMINATE"
    LIFECYCLE_ELIGIBILITY_RECORDED = "LIFECYCLE_ELIGIBILITY_RECORDED"
    APPROVAL_RECORDED = "APPROVAL_RECORDED"
    IDEMPOTENCY_RESERVATION_SIMULATED = "IDEMPOTENCY_RESERVATION_SIMULATED"
    READY_FOR_DISPATCH_REACHED = "READY_FOR_DISPATCH_REACHED"
    WOULD_DISPATCH = "WOULD_DISPATCH"
    WOULD_REQUIRE_RECONCILIATION = "WOULD_REQUIRE_RECONCILIATION"
    REPLAYED = "REPLAYED"
    FAILED_SAFE = "FAILED_SAFE"


class PaperDryRunFailureReason(StrEnum):
    """Stable dry-run failure reason codes."""

    INVALID_REQUEST = "INVALID_REQUEST"
    COMMAND_INELIGIBLE = "COMMAND_INELIGIBLE"
    EXTERNAL_EVIDENCE_REQUIRED = "EXTERNAL_EVIDENCE_REQUIRED"
    LIFECYCLE_TRANSITION_REJECTED = "LIFECYCLE_TRANSITION_REJECTED"
    STALE_REVISION = "STALE_REVISION"
    COMMAND_CONFLICT = "COMMAND_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    INTERNAL_INVARIANT = "INTERNAL_INVARIANT"
