"""Pure Paper qualification integration contracts and translators."""

from volcanoes.application.qualification.integration.contracts import (
    IntegrationOrderType,
    IntegrationTimeInForce,
    NormalizedRuntimeObservation,
    PaperIntegrationEnvironment,
    PaperRuntimeRequest,
    RuntimeActionKind,
    RuntimeActionRequest,
    RuntimeObservationType,
    RuntimeRequestKind,
    SafeMetadata,
    SafeOrderIntent,
    require_paper_environment,
)
from volcanoes.application.qualification.integration.errors import (
    IntegrationIdentityError,
    IntegrationTranslationError,
    PaperEnvironmentRequiredError,
    QualificationIntegrationError,
    RuntimeRequestValidationError,
    UnsafeIntegrationMetadataError,
    UnsupportedExecutionPlanError,
    UnsupportedRuntimeObservationError,
    UnsupportedRuntimeRequestError,
)
from volcanoes.application.qualification.integration.translation import (
    derive_integration_identity,
    execution_plan_to_runtime_action_request,
    observation_to_qualification_command,
    runtime_request_to_qualification_command,
)

__all__ = [
    "IntegrationIdentityError",
    "IntegrationOrderType",
    "IntegrationTimeInForce",
    "IntegrationTranslationError",
    "NormalizedRuntimeObservation",
    "PaperEnvironmentRequiredError",
    "PaperIntegrationEnvironment",
    "PaperRuntimeRequest",
    "QualificationIntegrationError",
    "RuntimeActionKind",
    "RuntimeActionRequest",
    "RuntimeObservationType",
    "RuntimeRequestKind",
    "RuntimeRequestValidationError",
    "SafeMetadata",
    "SafeOrderIntent",
    "UnsafeIntegrationMetadataError",
    "UnsupportedExecutionPlanError",
    "UnsupportedRuntimeObservationError",
    "UnsupportedRuntimeRequestError",
    "derive_integration_identity",
    "execution_plan_to_runtime_action_request",
    "observation_to_qualification_command",
    "require_paper_environment",
    "runtime_request_to_qualification_command",
]
